name: Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        host_os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.host_os }}

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - name: clippy
      if: ${{ !cancelled() }}
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: rustfmt
      if: ${{ !cancelled() }}
      run: cargo fmt --all -- --check
    - name: cargo check
      if: ${{ !cancelled() }}
      run: cargo check --all-targets --all-features

    - name: Build
      if: ${{ !cancelled() }}
      shell: bash
      run: cargo build --verbose

    - name: Run tests
      if: ${{ !cancelled() }}
      run: cargo test --verbose --all-features

    - name: Abort on error
      if: ${{ failure() }}
      run: echo "Some of jobs failed" && false
